# Generated by Django 3.2.4 on 2021-06-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='pub_date',
            new_name='pubdate',
        ),
    ]
